services:

  atacante:
    build: ./docker/atacante
    container_name: clt-atacante
    hostname: srv-atacante
    ports:
      - "2221:22"
    volumes:
      - ./scripts:/scripts
      - ./logs:/logs
    networks:
      - rede-clt
    restart: unless-stopped

  producao:
    build: ./docker/producao
    container_name: clt-producao
    hostname: srv-producao
    ports:
      - "2222:22"
    volumes:
      - dados-producao:/app/banco
      - dados-backup:/app/backup
      - ./logs:/app/logs
    networks:
      - rede-clt
    restart: unless-stopped

  dr:
    build: ./docker/dr
    container_name: clt-dr
    hostname: srv-dr
    ports:
      - "2223:22"
    volumes:
      - dados-dr:/app/banco
      - ./logs:/app/logs
    networks:
      - rede-clt
    restart: unless-stopped

volumes:
  dados-producao:
  dados-backup:
  dados-dr:

networks:
  rede-clt:
    driver: bridge